export const ROUTES = {
	home: '/',
	dashboard: '/dashboard',
	quickLog: '/log',
	monthlyWrapped: '/dashboard/wrapped',
	login: '/login',
	register: '/register',
	profile: '/profile',
	paymentMethods: '/profile/payment-methods',
	projects: '/projects',
	projectNew: '/projects/new',
	project: (id: string) => `/projects/${id}`,
	projectSettings: (id: string) => `/projects/${id}/settings`,
	projectTimesheet: (id: string) => `/projects/${id}/timesheet`,
	projectTodos: (id: string) => `/projects/${id}/todos`,
	projectInvoices: (id: string) => `/projects/${id}/invoices`,
	projectInvoiceNew: (id: string) => `/projects/${id}/invoices/new`,
	projectInvoice: (projectId: string, invoiceId: string) =>
		`/projects/${projectId}/invoices/${invoiceId}`,
	invoicePreview: (projectId: string) => `/projects/${projectId}/invoices/preview`,
} as const;
